"""Adding BaseConnection and TwitterConnection

Revision ID: 352bb5f4fff9
Revises: 11087341e403
Create Date: 2014-06-01 07:36:47.184217

"""

# revision identifiers, used by Alembic.
revision = '352bb5f4fff9'
down_revision = '11087341e403'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    'BaseConnection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(255), nullable=True),
    sa.Column('type', sa.Unicode(255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_connection', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
        ['username'], ['users.username'],
        name="baseconnection_username_fkey"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TwitterConnection',
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Unicode(255), nullable=True),
    sa.Column('access_key', sa.Unicode(255), nullable=True),
    sa.Column('access_secret', sa.Unicode(255), nullable=True),
    sa.Column('twitter_username', sa.Unicode(255), nullable=True),
    sa.Column('refresh_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
        ['connection_id'], ['BaseConnection.id'],
        name="twitterconnection_connectionid_fkey"),
    sa.PrimaryKeyConstraint('connection_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TwitterConnection')
    op.drop_table('BaseConnection')
    ### end Alembic commands ###
